complexity:
  CyclomaticComplexMethod:
    ignoreFunction:
      - "io.github.treesitter.ktreesitter.Query.Companion.init"
  TooManyFunctions:
    active: false
  LongParameterList:
    functionThreshold: 7

performance:
  SpreadOperator:
    excludes:
      - "**/*.kts"

style:
  WildcardImport:
    active: false
  ForbiddenComment:
    active: false
  UnusedPrivateProperty:
    excludes:
      - "**/commonMain/**"
  MagicNumber:
    ignoreNumbers:
      - "-1"
      - "0"
      - "1"
      - "2"
      - "3"
      - "10"
      - "16"
      - "0x7F"
  ReturnCount:
    max: 3
